"""Add User model

Revision ID: 246e5cc7bfaa
Revises: efa228cf9e51
Create Date: 2023-12-07 23:03:01.724194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246e5cc7bfaa'
down_revision = 'efa228cf9e51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
