"""Add game_user Association Table

Revision ID: ac817010476d
Revises: 246e5cc7bfaa
Create Date: 2023-12-07 23:12:41.952324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac817010476d'
down_revision = '246e5cc7bfaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
