"""Add game_user Association Table

Revision ID: fcf5c0cc0d23
Revises: ac817010476d
Create Date: 2023-12-07 23:20:08.820499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf5c0cc0d23'
down_revision = 'ac817010476d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
